### ISSUE TITLE
[BUG] ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.9.3

### ISSUE THREAD

**Issue by AleksCallebat** [NVIDIA/spark-rapids-container#47] opened 2023-05-26 07:35 UTC
**Describe the bug**
After following the step by step installation guide on Azure Databricks, I was met with a bug (ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.9.3). I can confirm that the cluster version is  10.4 LTS, with a worker type NC6_v3, and that the docker image is exactly the rapids-4-spark-databricks:23.02.0 from the repo. Is there an undocumented element to it ? 

**Steps/Code to reproduce bug**
Follow the tutorial on running rapids with Docker on Databricks

**Expected behavior**
A running container

**Environment details (please complete the following information)**
 - cloud : Azure
 - Spark : 10.4 LTS
 - Autoscaling : disabled
 - Multi-node
 - Photon : disabled
 - auto-shutdown : disabled
 - init script provided : file:/opt/spark-rapids/init.sh (from repo)

**Comment by GaryShen2008** [comment] 2023-05-30 23:30
Hi @AleksCallebat,

Thanks for reporting this issue.
I'm trying to reproduce it.

What symptom is this issue?
Is there any exception or error displayed when starting the cluster or running some job?

**Comment by GaryShen2008** [comment] 2023-05-31 06:45
I followed the instructions and created the cluster on Azure DB, then ran a simple spark sql query successfully.
Need more input about how to reproduce.

**Comment by AleksCallebat** [comment] 2023-05-31 13:38
Hello Gary, this happens when starting the docker image. Starting the cluster with the configuration above led me to the above error and a failure to start the cluster. Would you see any difference between your setup and the one I described above?

**Comment by GaryShen2008** [comment] 2023-05-31 15:34
I didn't see any error. My cluster is started normally.
I used same configurations you listed in the environment details, just not disabling auto-shutdown. (I don't think it impacts.)

Did your cluster fail to start? Where did you see the error?

**Comment by AleksCallebat** [comment] 2023-06-01 10:25
The cluster does indeed fail to start. It replicates this in the interface and in the logs where the error prevents the cluster to start. is it rapids-4-spark-databricks:23.02.0 ? If so then I guess I need to re-build it

**Comment by AleksCallebat** [comment] 2023-06-01 10:55
I am getting "Internal error message: Failed to launch spark container on instance <_redacted_>. Exception: Unexpected internal error, please contact Databricks support"

**Comment by GaryShen2008** [comment] 2023-06-02 09:25
Yes, I used 23.02.0, which I ran docker build from the latest source code(dev branch).
My test image is "garynv/fordb:rapids-4-spark-databricks-23.02.0", if you want to run a quick test.

**Comment by GaryShen2008** [comment] 2023-06-06 04:10
Hi @AleksCallebat ,

Could you share me more about the reproduce steps or have you tried the new docker build?

**Comment by AleksCallebat** [comment] 2023-06-06 15:01
Thanks Gary for the follow-up ! The image you provided seems to be running fine on Databricks. However I am under the impression that cuGraph & conda are not installed there ? 
import cugraph/import cudf doesn't work (No module named 'cugraph')
conda doesn't seem accessible via %sh either :(

**Comment by GaryShen2008** [comment] 2023-06-06 15:12
Did you change something in the docker, which may cause this issue?
I wonder if we can close this issue, if it can't be reproducible.

Yes, this is a container for Spark usage, so we don't install the cugraph and cudf.

**Comment by AleksCallebat** [comment] 2023-06-06 15:40
Would you have an image with cugraph/cudf already installed? If so happy to close it

**Comment by GaryShen2008** [comment] 2023-06-08 00:10
I don't have an image with cugraph/cudf.
Here's the doc about using Rapids on Databricks. Hope it helps.
https://docs.rapids.ai/deployment/stable/platforms/databricks/

**Comment by GaryShen2008** [comment] 2023-06-14 04:07
Hi @AleksCallebat,
Is it ok to close this issue? 
I think it should be caused by something else, not related to the image created in this repo for Databricks.
Or if you want to explain more details about what you did and how to reproduce it?

**Comment by GaryShen2008** [comment] 2023-06-26 05:30
Close it because it's not a bug for Spark container.

**Closed as completed by GaryShen2008** 2023-06-26 05:30 UTC
Labels: bug
